[package]
edition = "2021"
name = "rust"
version = "0.1.0"


[dependencies]
sha2 = "0.10"
bitcoin = {version = "0.32.5", features = ["serde"]}
hex = "0.4"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}
